name: Deploy updated templates

env:
  GO_VERSION: ^1.21

on:
  push:
    branches: [master]
    paths: ["templates/**"]
  workflow_dispatch:

jobs:
  docupdate:
    name: Deploy updated templates
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Build docs
        run: make install docs

      - name: Deploy to docs repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./templates/docs
          external_repository: evcc-io/docs
          publish_branch: main
          destination_dir: templates
          allow_empty_commit: false
          commit_message: Templates update
        if: ${{ success() }}
